[package]
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
description = "Basic implementation of a CosmWasm-20 compliant token"
documentation = "https://docs.cosmwasm.com"
edition = "2018"
homepage = "https://cosmwasm.com"
license = "Apache-2.0"
name = "ow20"
repository = "https://github.com/CosmWasm/cosmwasm-plus"
version = "0.5.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false

[dependencies]

cosmwasm-std = { version = "0.13.2", features = ["iterator"] }
cosmwasm-storage = { version = "0.13.2", features = ["iterator"] }
cw0 = "0.5.0"
cw2 = "0.5.0"
cw20 = "0.5.0"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.20" }

[dev-dependencies]
cosmwasm-schema = { version = "0.13.2" }
