[package]
authors = ["Oraichain Labs"]
edition = "2021"
license = "AGPL-3.0"
name = "vrfdkgp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.5" }
cosmwasm-schema = { version = "1.5" }
schemars = "0.8"
serde = { version = "1.0.204", default-features = false, features = ["derive"] }
thiserror = "1.0"
cw-utils = { workspace = true }