url: http://lcd.orai.io
chain_id: Oraichain
denom: orai
contract: orai15lv4hxxqew2jhfayfmad7y40zfr8zmgfulqdxj
ping_contract: orai14xs56wwfzk3dx5dysvahu0dmkz0wm38lrvn0wq
interval: 10000
ping_interval: 30000
