url: http://3.143.254.222:1317
chain_id: Oraichain-testnet
denom: orai
contract: orai1sj99eh3ltexddmsv85097wtxh6ngthwyaw7pq5
ping_contract: orai1nxjz9ys32w7xfwc7ecdm6ndzwuhp7c0d90n5pc
interval: 6000
ping_interval: 30000
