[package]
name = "drand-verify"
description = "A drand verification library."
version = "0.1.0"
authors = ["Simon Warta <simon@warta.it>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/drand-verify"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
js = ["hex", "wasm-bindgen"]

[dependencies]
# Needed due to missing re-exports in paired
fff = "0.2.0"
# Needed due to missing re-exports in paired
groupy = "0.3.0"
paired = "0.21"
sha2 = { workspace = true }
hex = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
hex = { workspace = true }
hex-literal = { workspace = true }
