[package]
name = "market_dino_data_marketplace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[dependencies]
cosmwasm-std = { version = "0.13.2" }
cosmwasm-storage = { version = "0.13.2" }
cw-storage-plus = { version = "0.5.0", features = ["iterator"] }
cw1155 = { path = "../../base/cw1155" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
schemars = "0.7"
