[package]
name = "market_rejected"
version = "0.6.0"
authors = ["ThanhTu <tu@orai.io>"]
edition = { workspace = true }
description = "Implementation of an NFT marketplace proxy contract using a governance"
repository = "https://github.com/oraichain/oraiwasm"
homepage = "https://orai.io"

[dependencies]
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
market = { workspace = true }
serde = { workspace = true, features = ["derive"] }
cw-utils = { workspace = true }
cosmwasm-schema = { workspace = true }
