[package]
name = "blsdkg"
version = "3.4.0"
authors = [
    "Vladimir Komendantskiy <komendantsky@gmail.com>",
    "Andreas Fackler <AndreasFackler@gmx.de>",
    "Peter van Nostrand <jnz@riseup.net>",
    "Andrew Gross <andogro@gmail.com>",
    "Nick Sanders <nsan1129@gmail.com>",
    "Marc Brinkmann <git@marcbrinkmann.de>",
    "Thanh tu <tu@orai.io>",
    "Duc Pham <duc@orai.io>",
]
categories = ["cryptography"]
keywords = ["pairing", "threshold"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/maidsafe/blsdkg"
description = "Pairing threshold cryptography"
edition = "2018"

[dependencies]
byteorder = "1.3.4"
ff = "0.6.0"
group = "0.6.0"
hex_fmt = "0.3.0"
log = "0.4.8"
pairing = "0.16.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
thiserror = "1.0.22"
zeroize = "1.1.0"
serde = { workspace = true, features = ["derive"] }
blst = { workspace = true, features = ["portable"] }
tiny-keccak = { workspace = true, features = ["sha3", "keccak"] }

bincode = { workspace = true, optional = true }
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = [
    "derive",
], optional = true }


[dev-dependencies]
base64 = "0.13.0"
criterion = "0.3.1"
hex = "0.4.3"
rand_xorshift = "0.2.0"
cosmwasm-schema = { workspace = true }

[[bench]]
name = "bench"
harness = false

[features]
codec-support = ["codec", "bincode"]
